<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="N15538C" name="Electron Tests" tests="4" failures="1" timestamp="16 Feb 2021 14:43:46 GMT" time="107.099" errors="0">
  <testcase name="test01_AddAndVerifyNewTask" time="6.754" classname="sanity.TodoListElectron"/>
  <testcase name="test02_AddAndVerifyNewTask" time="15.291" classname="sanity.TodoListElectron"/>
  <testcase name="test03_AddWithColorAndVerifyNewTask" time="21.858" classname="sanity.TodoListElectron">
    <failure type="java.lang.AssertionError" message="expected [5] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [1]
	at extensions.Verifications.verifyNumber(Verifications.java:66)
	at sanity.TodoListElectron.test03_AddWithColorAndVerifyNewTask(TodoListElectron.java:33)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test03_AddWithColorAndVerifyNewTask -->
  <testcase name="test04_MarkTask" time="9.858" classname="sanity.TodoListElectron"/>
</testsuite> <!-- Electron Tests -->
